import type { Partner, PartnerType, PartnerStatus, PickupStatus } from "@/types/database";

export const PARTNER_TYPE_LABELS_AR: Record<
  PartnerType,
  { label: string; icon: string; description: string }
> = {
  recycler: {
    label: "مصانع التدوير والصهر المعتمدة",
    icon: "Factory",
    description: "مصانع معتمدة بيئياً لفصل وتدوير البوردات واستخلاص المعادن النفيسة",
  },
  collection_point: {
    label: "نقاط التجميع والفروع",
    icon: "MapPin",
    description: "مراكز تسليم فورية في الجامعات، المراكز التجارية، والجمعيات",
  },
  transport: {
    label: "شركات النقل واللوجستيات",
    icon: "Truck",
    description: "أساطيل شحن ومندوبين لاستلام المخلفات المجدولة من المنازل والشركات",
  },
  business: {
    label: "شركاء الصيانة والتجزئة",
    icon: "Store",
    description: "متاجر ومراكز صيانة متخصصة في استقبال واستبدال الأجهزة القديمة",
  },
};

export const PARTNER_STATUS_LABELS_AR: Record<
  PartnerStatus,
  { label: string; badgeVariant: "default" | "secondary" | "destructive" }
> = {
  active: { label: "نشط ومتاح", badgeVariant: "default" },
  busy: { label: "مشغول / طاقة مكتملة", badgeVariant: "secondary" },
  inactive: { label: "متوقف مؤقتاً", badgeVariant: "destructive" },
};

export const PICKUP_STATUS_LABELS_AR: Record<
  PickupStatus,
  { label: string; badgeVariant: "default" | "secondary" | "outline" | "destructive" | "amber" }
> = {
  pending: { label: "بانتظار التعيين", badgeVariant: "amber" },
  assigned: { label: "تم التعيين للشريك", badgeVariant: "secondary" },
  scheduled: { label: "تم جدولة الموعد", badgeVariant: "secondary" },
  in_progress: { label: "المندوب في الطريق", badgeVariant: "amber" },
  completed: { label: "تم الاستلام بنجاح", badgeVariant: "default" },
  cancelled: { label: "ملغي", badgeVariant: "destructive" },
};

export const SEED_PARTNERS: Partner[] = [
  // 1. COLLECTION POINTS
  {
    id: "p1111111-1111-1111-1111-111111111111",
    name: "Cairo University Green Hub",
    name_ar: "مركز جامعة القاهرة لتدوير الإلكترونيات",
    type: "collection_point",
    phone: "0235678900",
    email: "greenhub@cu.edu.eg",
    address: "الحرم الجامعي الرئيسي، بجوار كلية الهندسة",
    city: "الجيزة",
    governorate: "الجيزة",
    latitude: 30.0264,
    longitude: 31.2118,
    status: "active",
    capacity_kg: 2000,
    working_hours: "يومياً من 9 صباحاً حتى 4 مساءً (عدا الجمعة)",
    notes: "يقبل جميع الأجهزة الإلكترونية والهواتف والشواحن",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p1111111-2222-2222-2222-222222222222",
    name: "Smart Village Drop-off Hub",
    name_ar: "نقطة تجميع القرية الذكية (Smart Village Hub)",
    type: "collection_point",
    phone: "01099887766",
    email: "smartdrop@e-waste.eg",
    address: "مبنى B12، القرية الذكية، طريق مصر إسكندرية الصحراوي",
    city: "6 أكتوبر",
    governorate: "الجيزة",
    latitude: 30.0766,
    longitude: 31.0205,
    status: "active",
    capacity_kg: 3000,
    working_hours: "الأحد إلى الخميس: 8:30 ص - 5:30 م",
    notes: "مخصص للشركات والأفراد بالقرية الذكية",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p1111111-3333-3333-3333-333333333333",
    name: "Resala Recycling Center Maadi",
    name_ar: "مركز جمعية رسالة لإعادة التدوير - المعادي",
    type: "collection_point",
    phone: "19450",
    email: "maadi@resala.org",
    address: "شارع النصر، تقاطع اللاسلكي، المعادي الجديدة",
    city: "المعادي",
    governorate: "القاهرة",
    latitude: 29.9765,
    longitude: 31.2825,
    status: "active",
    capacity_kg: 1500,
    working_hours: "يومياً من 10 صباحاً حتى 9 مساءً",
    notes: "استقبال المخلفات والتبرعات البيئية",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p1111111-4444-4444-4444-444444444444",
    name: "Alexandria Green Hub Smouha",
    name_ar: "نقطة تجميع الإسكندرية الخضراء - سموحة",
    type: "collection_point",
    phone: "034255100",
    email: "alexhub@e-waste.eg",
    address: "ميدان فيكتور عمانويل، سموحة",
    city: "سموحة",
    governorate: "الإسكندرية",
    latitude: 31.2166,
    longitude: 29.9567,
    status: "active",
    capacity_kg: 2500,
    working_hours: "يومياً من 10 صباحاً حتى 8 مساءً",
    notes: "نقطة رئيسية لخدمة محافظة الإسكندرية",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 2. TRANSPORT & LOGISTICS
  {
    id: "p2222222-1111-1111-1111-111111111111",
    name: "Green Express Logistics Fleet",
    name_ar: "أسطول جرين إكسبريس للشحن الأخضر",
    type: "transport",
    phone: "01011223344",
    email: "operations@greenexpress.eg",
    address: "المنطقة الصناعية، التجمع الخامس",
    city: "القاهرة الجديدة",
    governorate: "القاهرة",
    latitude: 30.0150,
    longitude: 31.4320,
    status: "active",
    capacity_kg: 10000,
    working_hours: "24/7 خدمات الاستلام المجدول",
    notes: "أسطول سيارات كهربائية ومندوبين مدربين",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p2222222-2222-2222-2222-222222222222",
    name: "Cairo Eco-Courier Network",
    name_ar: "شبكة مندوبي تدوير القاهرة الكبرى",
    type: "transport",
    phone: "01155443322",
    email: "fleet@cairoeco.eg",
    address: "شارع مصطفى النحاس، مدينة نصر",
    city: "مدينة نصر",
    governorate: "القاهرة",
    latitude: 30.0560,
    longitude: 31.3450,
    status: "active",
    capacity_kg: 8000,
    working_hours: "يومياً من 8 صباحاً حتى 10 مساءً",
    notes: "تغطية سريعة لكافة أحياء القاهرة والجيزة",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 3. RECYCLING PLANTS
  {
    id: "p3333333-1111-1111-1111-111111111111",
    name: "EGY-Recycle Metal Refining Plant",
    name_ar: "مصنع إيجي ريسايكل لاستخلاص المعادن النفيسة",
    type: "recycler",
    phone: "0238334455",
    email: "plant@egy-recycle.com",
    address: "المنطقة الصناعية الثالثة، مدينة 6 أكتوبر",
    city: "6 أكتوبر",
    governorate: "الجيزة",
    latitude: 29.9288,
    longitude: 30.9167,
    status: "active",
    capacity_kg: 50000,
    working_hours: "خطوط إنتاج مستمرة معتمدة بيئياً",
    notes: "مرخص من جهاز تنظيم إدارة المخلفات (WMRA)",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
