import type { Reward, RewardCategory, RedemptionStatus } from "@/types/database";

export const REWARD_CATEGORY_LABELS_AR: Record<
  RewardCategory,
  { label: string; icon: string; description: string }
> = {
  cash: {
    label: "سحب كاش ومحافظ إلكترونية",
    icon: "Wallet",
    description: "تحويل نقدي مباشر لمحفظة فودافون كاش أو حساب إنستاباي",
  },
  tree: {
    label: "زراعة شجرة بيئية",
    icon: "Trees",
    description: "غرس أشجار مثمرة باسمك لدعم البيئة ومكافحة الانبعاثات",
  },
  donation: {
    label: "تبرع لمستشفى 57357 والجمعيات",
    icon: "HeartHandshake",
    description: "تبرع بنقاطك لدعم علاج أطفال مستشفى 57357 والمشروعات الخيرية",
  },
  voucher: {
    label: "قسائم تسوق إلكترونية",
    icon: "ShoppingBag",
    description: "قسائم شراء رقمية فورية لنون وأمازون وكبرى المنصات",
  },
  discount: {
    label: "خصومات الهايبرماركت",
    icon: "Percent",
    description: "خصومات فورية لدى كارفور وكازيون وسلاسل التجزئة",
  },
  cashback: {
    label: "شحن رصيد ومحافظ",
    icon: "Coins",
    description: "شحن رصيد اتصالات وإنترنت منزلي",
  },
  product: {
    label: "منتجات صديقة للبيئة",
    icon: "Package",
    description: "منتجات معاد تدويرها وأجهزة مستدامة",
  },
};

export const REDEMPTION_STATUS_LABELS_AR: Record<
  RedemptionStatus,
  { label: string; badgeVariant: "default" | "secondary" | "outline" | "destructive" | "amber" }
> = {
  pending: { label: "قيد المراجعة والتحويل", badgeVariant: "amber" },
  approved: { label: "تمت الموافقة", badgeVariant: "default" },
  completed: { label: "مكتمل / صالحة", badgeVariant: "default" },
  used: { label: "تم الاستخدام", badgeVariant: "secondary" },
  expired: { label: "منتهية الصلاحية", badgeVariant: "destructive" },
  rejected: { label: "تم الرفض", badgeVariant: "destructive" },
  cancelled: { label: "ملغاة", badgeVariant: "outline" },
};

export const SEED_REWARDS: Reward[] = [
  // 1. CASH & WALLETS (Manual Approval MVP)
  {
    id: "c0000001-1111-1111-1111-111111111111",
    name: "Vodafone Cash 50 EGP Payout",
    title: "Vodafone Cash 50 EGP Payout",
    title_ar: "تحويل كاش 50 جنيه (فودافون كاش / إنستاباي)",
    description: "تحويل نقدي مباشر إلى محفظتك الإلكترونية أو عبر إنستاباي خلال 24 ساعة بمجرد المراجعة.",
    partner_name: "فودافون كاش / إنستاباي (Cash)",
    category: "cash",
    type: "cash",
    points_cost: 500,
    points_required: 500,
    monetary_value: 50.0,
    stock_quantity: 500,
    is_active: true,
    expiry_days: 30,
    metadata: { requires_phone: true, payout_type: "wallet" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c0000001-2222-2222-2222-222222222222",
    name: "Vodafone Cash 100 EGP Payout",
    title: "Vodafone Cash 100 EGP Payout",
    title_ar: "تحويل كاش 100 جنيه (فودافون كاش / إنستاباي)",
    description: "تحويل نقدي مباشر لرقم محفظتك الإلكترونية أو حساب إنستاباي بدون أي خصومات أو رسوم.",
    partner_name: "فودافون كاش / إنستاباي (Cash)",
    category: "cash",
    type: "cash",
    points_cost: 950,
    points_required: 950,
    monetary_value: 100.0,
    stock_quantity: 500,
    is_active: true,
    expiry_days: 30,
    metadata: { requires_phone: true, payout_type: "wallet" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c0000001-3333-3333-3333-333333333333",
    name: "Cash Transfer 200 EGP Payout",
    title: "Cash Transfer 200 EGP Payout",
    title_ar: "تحويل كاش 200 جنيه (إنستاباي / محفظة بنكية)",
    description: "سحب نقدي مباشر لأي محفظة بنكية أو إنستاباي في مصر بمراجعة فورية.",
    partner_name: "إنستاباي مصر (InstaPay)",
    category: "cash",
    type: "cash",
    points_cost: 1850,
    points_required: 1850,
    monetary_value: 200.0,
    stock_quantity: 300,
    is_active: true,
    expiry_days: 30,
    metadata: { requires_phone: true, payout_type: "instapay" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 2. TREE PLANTING (Environmental Impact)
  {
    id: "t0000001-1111-1111-1111-111111111111",
    name: "Plant an Olive or Fruit Tree in Egypt",
    title: "Plant an Olive or Fruit Tree in Egypt",
    title_ar: "زراعة شجرة زيتون أو فاكهة مثمرة باسمك",
    description: "مساهمة بيئية حقيقية لغرس شجرة مثمرة في إحدى المحافظات المصرية باسمك أو إهدائها لمن تحب مع شهادة رقمية معتمدة.",
    partner_name: "مبادرة شجرها ومصر الخضراء (Green Egypt)",
    category: "tree",
    type: "tree",
    points_cost: 400,
    points_required: 400,
    monetary_value: 40.0,
    stock_quantity: 1000,
    is_active: true,
    expiry_days: 365,
    metadata: { requires_dedication_name: true, impact_co2_kg: 25 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "t0000001-2222-2222-2222-222222222222",
    name: "Plant 3 Trees for Clean Air",
    title: "Plant 3 Trees for Clean Air",
    title_ar: "غرس 3 أشجار لتنقية الهواء والحد من الانبعاثات",
    description: "مشروع تشجير متكامل لغرس 3 أشجار في المناطق السكنية والمدارس لخفض البصمة الكربونية.",
    partner_name: "مبادرة شجرها ومصر الخضراء (Green Egypt)",
    category: "tree",
    type: "tree",
    points_cost: 1100,
    points_required: 1100,
    monetary_value: 120.0,
    stock_quantity: 500,
    is_active: true,
    expiry_days: 365,
    metadata: { requires_dedication_name: true, impact_co2_kg: 75 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 3. DONATIONS (Hospital 57357 & Resala)
  {
    id: "d0000001-1111-1111-1111-111111111111",
    name: "50 EGP Donation to 57357 Hospital",
    title: "50 EGP Donation to 57357 Hospital",
    title_ar: "تبرع بقيمة 50 جنيه لمستشفى 57357 لعلاج سرطان الأطفال",
    description: "تحويل نقاط إعادة التدوير لدعم علاج ورعاية أطفال مستشفى 57357 مع إصدار إيصال تبرع رقمي فوري.",
    partner_name: "مستشفى سرطان الأطفال 57357",
    category: "donation",
    type: "donation",
    points_cost: 450,
    points_required: 450,
    monetary_value: 50.0,
    stock_quantity: 9999,
    is_active: true,
    expiry_days: 365,
    metadata: { charity: "57357", tax_deductible: true },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "d0000001-2222-2222-2222-222222222222",
    name: "100 EGP Donation to 57357 Hospital",
    title: "100 EGP Donation to 57357 Hospital",
    title_ar: "تبرع بقيمة 100 جنيه لمستشفى 57357 لعلاج سرطان الأطفال",
    description: "مساهمة كريمة في توفير جرعات العلاج والأجهزة الطبية المتطورة بمستشفى 57357.",
    partner_name: "مستشفى سرطان الأطفال 57357",
    category: "donation",
    type: "donation",
    points_cost: 900,
    points_required: 900,
    monetary_value: 100.0,
    stock_quantity: 9999,
    is_active: true,
    expiry_days: 365,
    metadata: { charity: "57357", tax_deductible: true },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "d0000001-3333-3333-3333-333333333333",
    name: "50 EGP Donation to Resala Green Charity",
    title: "50 EGP Donation to Resala Green Charity",
    title_ar: "تبرع بيئي واجتماعي بقيمة 50 جنيه لجمعية رسالة",
    description: "دعم أنشطة جمعية رسالة في التنمية المجتمعية ومساعدة الأسر الأكثر احتياجاً وإعادة التدوير.",
    partner_name: "جمعية رسالة (Resala Charity)",
    category: "donation",
    type: "donation",
    points_cost: 450,
    points_required: 450,
    monetary_value: 50.0,
    stock_quantity: 9999,
    is_active: true,
    expiry_days: 365,
    metadata: { charity: "resala", tax_deductible: true },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // 4. VOUCHERS & DISCOUNTS
  {
    id: "c1111111-1111-1111-1111-111111111111",
    name: "Noon Egypt 50 EGP Voucher",
    title: "Noon Egypt 50 EGP Voucher",
    title_ar: "قسيمة شراء نون مصر بقيمة 50 جنيه",
    description: "قسيمة شراء صالحة لجميع المنتجات على منصة نون مصر بدون حد أدنى للطلب.",
    partner_name: "نون مصر (Noon)",
    category: "voucher",
    type: "voucher",
    points_cost: 500,
    points_required: 500,
    monetary_value: 50.0,
    stock_quantity: 150,
    is_active: true,
    expiry_days: 45,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c1111111-2222-2222-2222-222222222222",
    name: "Noon Egypt 100 EGP Voucher",
    title: "Noon Egypt 100 EGP Voucher",
    title_ar: "قسيمة شراء نون مصر بقيمة 100 جنيه",
    description: "قسيمة شراء صالحة لجميع المنتجات الإلكترونية والمنزلية على نون مصر.",
    partner_name: "نون مصر (Noon)",
    category: "voucher",
    type: "voucher",
    points_cost: 950,
    points_required: 950,
    monetary_value: 100.0,
    stock_quantity: 100,
    is_active: true,
    expiry_days: 45,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c2222222-1111-1111-1111-111111111111",
    name: "Amazon Egypt 50 EGP Gift Card",
    title: "Amazon Egypt 50 EGP Gift Card",
    title_ar: "بطاقة هدايا أمازون مصر 50 جنيه",
    description: "رصيد يتم إضافته مباشرة إلى حسابك في أمازون مصر للشراء من ملايين المنتجات.",
    partner_name: "أمازون مصر (Amazon)",
    category: "voucher",
    type: "voucher",
    points_cost: 500,
    points_required: 500,
    monetary_value: 50.0,
    stock_quantity: 120,
    is_active: true,
    expiry_days: 60,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c2222222-2222-2222-2222-222222222222",
    name: "Amazon Egypt 150 EGP Gift Card",
    title: "Amazon Egypt 150 EGP Gift Card",
    title_ar: "بطاقة هدايا أمازون مصر 150 جنيه",
    description: "رصيد أمازون مصر للاستخدام في العروض والمنتجات الأصلية.",
    partner_name: "أمازون مصر (Amazon)",
    category: "voucher",
    type: "voucher",
    points_cost: 1400,
    points_required: 1400,
    monetary_value: 150.0,
    stock_quantity: 80,
    is_active: true,
    expiry_days: 60,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c4444444-1111-1111-1111-111111111111",
    name: "Carrefour Egypt 50 EGP Coupon",
    title: "Carrefour Egypt 50 EGP Coupon",
    title_ar: "قسيمة خصم كارفور مصر 50 جنيه",
    description: "صالحة للاستخدام في جميع فروع كارفور مصر أو عبر التطبيق الإلكتروني.",
    partner_name: "كارفور مصر (Carrefour)",
    category: "discount",
    type: "discount",
    points_cost: 480,
    points_required: 480,
    monetary_value: 50.0,
    stock_quantity: 100,
    is_active: true,
    expiry_days: 30,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c5555555-1111-1111-1111-111111111111",
    name: "WE Telecom Internet 50 EGP Credit",
    title: "WE Telecom Internet 50 EGP Credit",
    title_ar: "رصيد إنترنت منزلي WE بقيمة 50 جنيه",
    description: "سداد جزئي أو شحن باقة إضافية للإنترنت المنزلي من وي (المصرية للاتصالات).",
    partner_name: "المصرية للاتصالات (WE)",
    category: "voucher",
    type: "voucher",
    points_cost: 490,
    points_required: 490,
    monetary_value: 50.0,
    stock_quantity: 90,
    is_active: true,
    expiry_days: 30,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
